---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: coffee-cluster-control-plane-unhealthy-5m
  namespace: default
spec:
  clusterName: coffee-cluster
  maxUnhealthy: 1
  nodeStartupTimeout: 15m
  selector:
    matchExpressions:
      - key: cluster.x-k8s.io/control-plane
        operator: Exists
  unhealthyConditions:
  - type: Ready
    status: "Unknown"
    timeout: 300s
  - type: Ready
    status: "False"
    timeout: 300s
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: coffee-cluster-worker-unhealthy-5m
  namespace: default
spec:
  clusterName: coffee-cluster
  maxUnhealthy: 40%
  nodeStartupTimeout: 15m
  selector:
    matchLabels:
      cluster.x-k8s.io/deployment-name: coffee-cluster-workers
  unhealthyConditions:
  - type: Ready
    status: Unknown
    timeout: 300s
  - type: Ready
    status: "False"
    timeout: 300s