apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: coffee-cluster-worker-config
  namespace: default
spec:
  template:
    spec:
      generateType: worker
      configPatches:
        # === Prepare for Cilium ===
        - op: add
          path: /cluster/network/cni
          value:
            name: none
        - op: add
          path: /cluster/proxy
          value:
            disabled: true
        # === DRBD (LINSTOR Satellite) ===
        # - op: add
        #   path: /machine/kernel/modules
        #   value:
        #     - name: drbd
        #       parameters:
        #         - usermode_helper=disabled
        #     - name: drbd_transport_tcp
        # - op: add
        #   path: /machine/nodeLabels
        #   value:
        #     storage.talos.dev/linstor: "true"

        # === Host DNS (so kubelet can resolve kubernetes.default before Cilium starts) ===
        - op: add
          path: /machine/features/hostDNS
          value:
            enabled: true
            forwardKubeDNSToHost: true

        # === Discovery (disable built-in Talos discovery; CAPI is authoritative) ===
        - op: add
          path: /cluster/discovery
          value:
            enabled: false
            registries:
              kubernetes:
                disabled: true
              service:
                disabled: true
        # === Network (static layout, no DHCP, fixed interface name) ===
        - op: add
          path: /machine/install/extraKernelArgs
          value:
            - net.ifnames=0      
        - op: add
          path: /machine/network/interfaces
          value:
            - interface: eth0
              dhcp: true
              # addresses:
              #   - 192.168.100.221/24    # example — assign one address per node
              routes:
                - network: 0.0.0.0/0
                  gateway: 192.168.100.1

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: coffee-cluster-workers
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: coffee-cluster
spec:
  clusterName: coffee-cluster
  replicas: 2
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: coffee-cluster
        node-role.kubernetes.io/node: ""
    spec:
      clusterName: coffee-cluster
      version: v1.34.0
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: coffee-cluster-worker-config
          namespace: default
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: ProxmoxMachineTemplate
        name: coffee-cluster-worker-template
        namespace: default
      
      
      
